url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Randall Kliman" # the name of your site, e.g. ACME Corp.
sass:
  sass_dir: css
  style: compressed

collections:
  projects:
    output: true

# build settings
markdown: kramdown
